### ISSUE TITLE
WOL to Windows 10 works on Android but not iOS app

### ISSUE THREAD

**Issue by dustins5523** [herzhenr/simple-wake-on-lan#19]
Setting up WOL for my daughters PC, I have this app for iOS and Android. My phone, the Android wakes the PC perfectly. I copied the info to the iOS app and it does not wake the PC

Before I found this app I was using another iOS WOL app that would only wake her PC if it had recently been shutdown. I changed a million different settings on the PC and that never changed.

But using your app on Android her PC can be off for a week and the Android app fires it right up. But iOS cant do anything. It says it successfully sent the packet, but does not wake up the machine.

We are on the same network as the PC. The PC is hardwired. We are both on my own VPN using wireguard as well if that makes a difference. The VPN is on the same network. The app doesn't work with or without the VPN on.

**Comment by herzhenr** [comment]
Hi there,
I can think of one possible cause for the problem. Have you ever pressed the `Add Devices` button on the `Home` page on the iOS device? I think my app only asks for the network permission once when you enter this screen. Do you see devices in the discover screen popping up? Or do you see the correct online state on the home page of a device? (The small green or red dot next to a device icon? If not maybe you have declined the network permission when it popped up first. Then the easiest thing would be to delete and reinstall the app and then check that you allow network access.

You can also check the ip in the `About` screen of the device (`Device Info` > `IP`). Is there an IP shown? Is it similar to the IP from the android device (same subnet)? This could help to narrow down where the problem comes from.

**Comment by dustins5523** [comment]
YES!! Thank you!

The first time I set it up I declined all that because I didn't want to scan, I knew the IP. But reinstalling and allowing everything and scanning fixed my issue. Thank you so much!

**Comment by herzhenr** [comment]
Awesome, glad I could help!
But I should change the behaviour of the app when the network permission is declined because it isn't clear at all where the problem comes from. Maybe a message should pop up saying you have to allow network access for the app to function properly every time a user tries to wake a devices or clicks on the `Add Device` page.

I close this Issue and create a new one to implement such a behaviour in the future. Feel free to open this Issue again or a new one if something other isn't functioning as it should!
